# docker-compose.yml
version: "3.8"

networks:
  helloworld:
    driver: bridge

services:

  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html
    networks:
      - helloworld

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - helloworld

  composer:
    build: ./docker/composer
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: install
    depends_on:
      - php
    user: laravel
    networks:
      - helloworld
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  npm:
    image: node
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - helloworld
    entrypoint: [ 'npm' ]

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: helloworld
      MYSQL_USER: helloworld
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - helloworld

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8085:80
    networks:
      - helloworld

  artisan:
    build: ./docker/composer
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - helloworld

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - helloworld

  # jenkins:
  #   build: ./docker/jenkins
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000"
  #   volumes:
  #     - ./src:/var/www/html
  #   networks:
  #     - helloworld
